create table if not exists public.agents (
  id integer primary key,
  name text,
  image text,
  rating numeric,
  reviews integer,
  listings_count integer,
  whatsapp text,
  email text
);

create table if not exists public.properties (
  id integer primary key,
  title text,
  type text,
  rent text,
  location text,
  distance text,
  image text,
  images text[] not null default '{}'::text[],
  amenities text[] not null default '{}'::text[],
  agent_id integer,
  description text,
  constraint properties_agent_id_fkey
    foreign key (agent_id)
    references public.agents (id)
    on update no action
    on delete no action
);

create table if not exists public.reviews (
  id integer generated by default as identity primary key,
  client_name text not null,
  rating integer not null,
  comment text not null,
  created_at timestamp with time zone not null default now(),
  property_id integer not null,
  constraint reviews_property_id_fkey
    foreign key (property_id)
    references public.properties (id)
    on update no action
    on delete cascade
);

create index if not exists properties_agent_id_idx on public.properties (agent_id);
create index if not exists reviews_property_id_idx on public.reviews (property_id);
